### ISSUE TITLE
You should have more brain than protecting a neo-nazi

### ISSUE THREAD

**Issue by JabbaDesilijicTiure** [imachug/gitcenter#3]
He is a fucking Ukrainian neo-nazi. https://github.com/HelloZeroNet/ZeroNet/pull/2652

Even from hes profile picture can tell that, the picture he use is exactly the same like this guy down: 
![nazi](https://user-images.githubusercontent.com/71508279/96337207-bf7fb300-1074-11eb-81ff-f64137264e44.jpeg)

Ukrainian neo-nazi militias. 

For that matter American neo-nazis going to Ukraine and bringing cash from the U.S. State Department as well to fincance this terrorists: https://www.vice.com/en/article/jgqex8/neo-nazi-terror-group-the-base-discussed-training-pipeline-to-ukraine-war

ZeroNet should be not used by any fascist shit and they should be banned from the repository instead of me.

**Comment by imachug** [comment]
I do not care about politics, and I do not get a person talking to offend them. I do not care who you are if you do the right thing. ZeroNet is a place for refugees, not only cisgender white male. So, sorry -- you are wrong.

**Comment by JabbaDesilijicTiure** [comment]
ZeroNet is a place for refugees :+1:

**Comment by JabbaDesilijicTiure** [comment]
But he is not a refugee, he is a neo-nazi shit from Ukraine.

**Comment by imachug** [comment]
I live in a crazy country ruled by a crazy government that is willing to invade other countries. So, sorry, I am not judging others for strange political views.

**Comment by JabbaDesilijicTiure** [comment]
Russia must defend itself! Since the USSR is dissolved the NATO keeps expanding and it is on the doorstep of Russia. If I'm the Russian government I would just bomb the shit out of EU and NATO. So your government is not that bad than you think.

**Comment by imachug** [comment]
The grass is always greener. Please -- just don't start. I don't want to talk about politics.

**Comment by gukandrew** [comment]
![Screenshot_2020-10-20 imachug gitcenter](https://user-images.githubusercontent.com/36536011/96570528-2a2e2a00-12d3-11eb-8d1d-c4e9320aa07e.png)

@JabbaDesilijicTiure internet remember everything. And everyone who want, will know who you are.
